language: python
dist: trusty

python:
  - 2.7

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install -qq ccache
  - sudo apt-get install -qq libgsl0-dev

  - mkdir -p ~/.config/matplotlib
  - mkdir -p ~/.matplotlib
  - touch ~/.config/matplotlib/matplotlibrc
  - touch ~/.matplotlib/matplotlibrc
  - touch ~/.matplotlibrc
  - 'echo "backend: agg" >> ~/.config/matplotlib/matplotlibrc'
  - 'echo "backend: agg" >> ~/.matplotlib/matplotlibrc'
  - 'echo "backend: agg" >> ~/.matplotlibrc'

  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build

script:
  - export CONDA_PACKAGE_VERSION="${TRAVIS_TAG:-$(date +%Y.%m.%d)}"
  # remove leading v from tags if they exist
  - CONDA_PACKAGE_VERSION="$(sed s/^v// <<<$CONDA_PACKAGE_VERSION)"
  - conda build . -c probcomp

after_success:
  - bash conda/upload.sh
